<?php 

define('TELEGRAM_TOKEN', ENV['TELEGRAM_TOKEN']);
define('MIGRATIONS_RUNNED', (bool) ENV['MIGRATIONS_RUNNED']);
define('MYSQL_DATABASE', ENV['MYSQL_DATABASE']);
define('MYSQL_USER', ENV['MYSQL_USER']);
define('MYSQL_PASSWORD', ENV['MYSQL_PASSWORD']);
